# sets parser options.
parser:
  # enables type inference for schemas. Schema parser will try to detect schema type by its properties.
  infer_types: true
  #  enables remote references resolving. See https://github.com/ogen-go/ogen/issues/385.
  allow_remote: true
  # is maximum depth of schema generation. Default is 1000.
  depth_limit: 1000

# sets generator options.
generator:
  # sets generator features.
  features:
    enable:
      # Enables paths server generation
      - 'paths/server'
    disable:
      # Disables paths client generation
      - 'paths/client'
      # Disables paths server generation
      - 'paths/server'
      # Disables webhooks client generation
      - 'webhooks/client'
      # Disables webhooks server generation
      - 'webhooks/server'
      # Disables client usage in security source implementations
      - 'client/security/reentrant'
      # Disables validation of client requests
      - 'client/request/validation'
      # Disables validation of server responses
      - 'server/response/validation'
      # Disables OpenTelemetry integration
      - 'ogen/otel'
      # Disables stub Handler generation
      - 'ogen/unimplemented'
      # Disables example tests generation
      - 'debug/example_tests'

  # functions to ignore
  ignore_not_implemented: ["all"]

# is a path to expanded spec.
expand: ""