// Code generated by ogen, DO NOT EDIT.

package service

// GetGetInternalServerError is response for GetGet operation.
type GetGetInternalServerError struct{}

func (*GetGetInternalServerError) getGetRes() {}

// Ref: #/components/schemas/GetResponse
type GetResponse struct {
	Services []Service `json:"services"`
}

// GetServices returns the value of Services.
func (s *GetResponse) GetServices() []Service {
	return s.Services
}

// SetServices sets the value of Services.
func (s *GetResponse) SetServices(val []Service) {
	s.Services = val
}

func (*GetResponse) getGetRes() {}

// Ref: #/components/schemas/Service
type Service struct {
	Name string `json:"name"`
	IP   string `json:"ip"`
}

// GetName returns the value of Name.
func (s *Service) GetName() string {
	return s.Name
}

// GetIP returns the value of IP.
func (s *Service) GetIP() string {
	return s.IP
}

// SetName sets the value of Name.
func (s *Service) SetName(val string) {
	s.Name = val
}

// SetIP sets the value of IP.
func (s *Service) SetIP(val string) {
	s.IP = val
}
