// Code generated by ogen, DO NOT EDIT.

package addressserver

// GetGetInternalServerError is response for GetGet operation.
type GetGetInternalServerError struct{}

func (*GetGetInternalServerError) getGetRes() {}

// Ref: #/components/schemas/GetResponse
type GetResponse struct {
	Services []Service `json:"services"`
}

// GetServices returns the value of Services.
func (s *GetResponse) GetServices() []Service {
	return s.Services
}

// SetServices sets the value of Services.
func (s *GetResponse) SetServices(val []Service) {
	s.Services = val
}

func (*GetResponse) getGetRes() {}

// Ref: #/components/schemas/Service
type Service struct {
	ID    string `json:"id"`
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetID returns the value of ID.
func (s *Service) GetID() string {
	return s.ID
}

// GetKey returns the value of Key.
func (s *Service) GetKey() string {
	return s.Key
}

// GetValue returns the value of Value.
func (s *Service) GetValue() string {
	return s.Value
}

// SetID sets the value of ID.
func (s *Service) SetID(val string) {
	s.ID = val
}

// SetKey sets the value of Key.
func (s *Service) SetKey(val string) {
	s.Key = val
}

// SetValue sets the value of Value.
func (s *Service) SetValue(val string) {
	s.Value = val
}
