// Code generated by ogen, DO NOT EDIT.

package signals

// GetGetInternalServerError is response for GetGet operation.
type GetGetInternalServerError struct{}

func (*GetGetInternalServerError) getGetRes() {}

// Ref: #/components/schemas/SignalResponse
type SignalResponse struct {
	ID   int       `json:"id"`
	Name string    `json:"name"`
	X    []float64 `json:"x"`
	Y    []float64 `json:"y"`
}

// GetID returns the value of ID.
func (s *SignalResponse) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *SignalResponse) GetName() string {
	return s.Name
}

// GetX returns the value of X.
func (s *SignalResponse) GetX() []float64 {
	return s.X
}

// GetY returns the value of Y.
func (s *SignalResponse) GetY() []float64 {
	return s.Y
}

// SetID sets the value of ID.
func (s *SignalResponse) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *SignalResponse) SetName(val string) {
	s.Name = val
}

// SetX sets the value of X.
func (s *SignalResponse) SetX(val []float64) {
	s.X = val
}

// SetY sets the value of Y.
func (s *SignalResponse) SetY(val []float64) {
	s.Y = val
}

func (*SignalResponse) getGetRes() {}
