// Code generated by ogen, DO NOT EDIT.

package statistics

// OperationName is the ogen operation name
type OperationName = string

const (
	StatisticsPostOperation OperationName = "StatisticsPost"
)
