// Code generated by ogen, DO NOT EDIT.

package statistics

// StatisticsPostInternalServerError is response for StatisticsPost operation.
type StatisticsPostInternalServerError struct{}

func (*StatisticsPostInternalServerError) statisticsPostRes() {}

// Ref: #/components/schemas/StatisticsRequest
type StatisticsRequest struct {
	Values []float64 `json:"values"`
}

// GetValues returns the value of Values.
func (s *StatisticsRequest) GetValues() []float64 {
	return s.Values
}

// SetValues sets the value of Values.
func (s *StatisticsRequest) SetValues(val []float64) {
	s.Values = val
}

// Ref: #/components/schemas/StatisticsResponse
type StatisticsResponse struct {
	Max     float64 `json:"max"`
	Min     float64 `json:"min"`
	Average float64 `json:"average"`
}

// GetMax returns the value of Max.
func (s *StatisticsResponse) GetMax() float64 {
	return s.Max
}

// GetMin returns the value of Min.
func (s *StatisticsResponse) GetMin() float64 {
	return s.Min
}

// GetAverage returns the value of Average.
func (s *StatisticsResponse) GetAverage() float64 {
	return s.Average
}

// SetMax sets the value of Max.
func (s *StatisticsResponse) SetMax(val float64) {
	s.Max = val
}

// SetMin sets the value of Min.
func (s *StatisticsResponse) SetMin(val float64) {
	s.Min = val
}

// SetAverage sets the value of Average.
func (s *StatisticsResponse) SetAverage(val float64) {
	s.Average = val
}

func (*StatisticsResponse) statisticsPostRes() {}
