// Code generated by ogen, DO NOT EDIT.

package statistics

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func encodeStatisticsPostResponse(response StatisticsPostRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *StatisticsResponse:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *StatisticsPostInternalServerError:
		w.WriteHeader(500)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}
